default:
	# clang++ -Wall -Werror -Weffc++ -Wextra -pedantic-errors -std=c++17 day_02a.cpp -o day2a
	# ./day2a

	clang++ -Wall -Werror -Weffc++ -Wextra -pedantic-errors -std=c++17 day_02b.cpp -o day2b
	./day2b
